import {expeditionCombatTurn,restoreExpeditionCombat} from './combat.js';

const COLUMNS=[[0,2],[1,3],[4]],d=(target,ratio,extra={})=>({type:'damage',target,ratio,...extra}),mark=target=>({type:'vulnerable',target,ratio:0}),cold=(target,stacks)=>({type:'chill',target,ratio:0,stacks}),pull=target=>({type:'pull',target,ratio:0}),back=(target,ratio)=>({type:'return',target,ratio,rounds:2});
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
// Authored data only. The same combat executor handles damage, fixed returns,
// protection, finite counter charges, boss warnings and active-body targeting.
// Boss returns intentionally take two rounds: a slow boss may cast after every
// ally acted, so rounds:1 would foretell and deal lethal damage in the same
// accepted receipt. Ordinary species/enemy recall remains rounds:1 in world.
const ACTIONS=freeze({
 meadow:{attack:[d('column',.8)],skill1:[mark('column'),d('column',1.4)]},
 blossom:{attack:[{type:'split',target:'adjacent',ratio:.55,maxTargets:2}],skill1:[{type:'split',target:'all',ratio:.85,maxTargets:5}]},
 autumn:{attack:[d('single',.6),back('single',.8)],skill1:[back('column',1.2)]},
 snow:{attack:[cold('column',1),d('column',.4)],skill1:[d('column',1.8)]},
 moon:{attack:[d('adjacent',.65)],skill1:[{type:'protection',target:'ally',ratio:1.8},d('adjacent',.9)]},
 fire:{attack:[d('adjacent',.7)],skill1:[back('all',1.1)]},
 shadow:{attack:[pull('column'),d('column',.55)],skill1:[pull('column'),mark('column'),d('column',.9)]},
 dream:{attack:[d('single',.7)],skill1:[{type:'counter',target:'self',ratio:1.2,charges:1},{type:'protection',target:'self',ratio:1}]}
});
const step=(phase,kind,target,tell,recovery=false)=>({phase,kind,target,tell,recovery});
export const EXPEDITION_BOSS_BEHAVIORS=freeze({
 meadow:{name:'가시뿔 수호자',steps:[step('직선 조준','attack','column','같은 열 앞뒤를 가볍게 찌릅니다.'),step('가시뿔 돌진','skill1','previous-column','조준한 열에 취약을 남기고 관통합니다.'),step('뿔 회수','guard','front','뿔을 뽑으며 방어합니다. 교대와 보호를 준비하세요.',true)]},
 blossom:{name:'천개의 꽃잎',steps:[step('두 갈래 발아','attack','crowd','가까운 실제 두 대상을 향해 꽃잎이 갈라집니다.'),step('꽃잎 만개','skill1','crowd','출전한 실제 대상 모두에게 유한 꽃잎이 퍼집니다.'),step('꽃잎 접기','guard','front','갈라진 꽃잎을 접으며 방어합니다.',true),step('잔가지 훑기','attack','exposed','보호가 적은 자리 주변을 두 갈래로 훑습니다.')]},
 autumn:{name:'낙엽 사냥꾼',steps:[step('귀환 경로 예약','skill1','column','선택한 열의 실제 대상에 한 라운드 대응 뒤 귀환을 예고합니다.'),step('귀환 기다림','guard','front','예약한 대상에게 낙엽이 돌아옵니다. 방어하거나 교대하세요.',true),step('왕로 사냥','attack','front','전열을 베고 그 같은 개체에 귀환을 예약합니다.')]},
 snow:{name:'백설의 거인',steps:[step('찬 숨결','attack','fast-column','빠른 개체가 있는 열에 냉기를 남깁니다.'),step('서리 축적','attack','cold-column','실제 냉기가 가장 쌓인 열을 한 번 더 식힙니다.'),step('얼음열 파쇄','skill1','cold-column','느려진 열을 강하게 내려칩니다.'),step('눈보라 가라앉힘','guard','front','거인이 방어하며 숨을 고릅니다.',true)]},
 moon:{name:'월륜 수호자',steps:[step('위성 호위','skill1','exposed','살아 있는 자기 전열을 보호하고 노출된 자리 주변을 압박합니다.'),step('달빛 궤도','attack','exposed','보호가 적은 자리와 실제 인접 대상을 훑습니다.'),step('공전 복귀','guard','front','위성이 돌아오는 동안 방어합니다.',true),step('남은 위성 출격','attack','crowd','모여 있는 실제 진형을 궤도로 압박합니다.')]},
 fire:{name:'용암의 심장',steps:[step('지연 폭발 예약','skill1','exposed','현재 출전한 개체마다 한 라운드 대응 뒤 폭발을 예고합니다.'),step('불씨 추격','attack','wounded','폭발 뒤 가장 다친 자리 주변에 불씨를 보냅니다.'),step('심장 냉각','guard','front','열을 식히며 방어합니다. 정비할 시간입니다.',true),step('화염 확산','attack','crowd','다시 모인 진형 주변에 화염을 퍼뜨립니다.')]},
 shadow:{name:'심연의 문지기',steps:[step('빈 전열 끌기','attack','gap-column','전열이 비어 있으면 같은 열 뒤의 개체를 앞으로 끌어옵니다.'),step('심연 압축','skill1','previous-column','그 열을 다시 끌어 취약을 쌓고 압축합니다.'),step('중력 안정','guard','front','끌어당김을 가라앉히며 방어합니다.',true)]},
 dream:{name:'거울의 여왕',steps:[step('반격 거울','skill1','front','보호막과 유한 한 번 반격을 준비합니다. 무작정 공격하지 마세요.'),step('관측한 적 되치기','attack','attacker','실제로 자신을 공격했던 전열 개체를 되칩니다.'),step('거울 열린 틈','guard','front','반격이 끝난 틈에서 방어합니다.',true),step('유리 정면 찌르기','attack','front','공격을 기다리지 않고 실제 정면 공격으로 압박합니다.')]}
});
export function expeditionBossActionPattern(gardenId){const data=Object.hasOwn(ACTIONS,gardenId)?ACTIONS[gardenId]:null;return data?freeze({attack:data.attack,skill1:data.skill1,skill2:data.skill1,awaken:data.skill1}):null;}
const alive=u=>u.hp>0&&!u.dead&&u.slot<5,slotOrder=(a,b)=>a.slot-b.slot||a.id.localeCompare(b.id),columnOf=u=>COLUMNS.findIndex(c=>c.includes(u.slot));
function availableTargets(s,actor,kind){const foes=s.units.filter(u=>alive(u)&&u.side!==actor.side).sort(slotOrder),ops=actor.actions[kind]||[];const wide=ops.some(o=>['column','all','adjacent'].includes(o.target)||o.target==='single'&&o.ignoreFront),front=foes.filter(u=>u.slot<2);return wide||!front.length?foes:front;}
function previousColumn(s,actor,foes){const hits=s.log.filter(e=>e.type==='damage'&&e.unitId===actor.id&&e.round===s.round-1);for(const e of hits){const unit=foes.find(u=>u.id===e.targetId);if(unit)return columnOf(unit);}return null;}
function select(s,actor,kind,mode){const foes=availableTargets(s,actor,kind);if(!foes.length)return null;if(mode==='front')return foes[0];if(mode==='wounded')return [...foes].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||slotOrder(a,b))[0];if(mode==='exposed')return [...foes].sort((a,b)=>a.status.protection-b.status.protection||Number(a.guarding)-Number(b.guarding)||slotOrder(a,b))[0];if(mode==='fast-column')return [...foes].sort((a,b)=>b.speed*(b.status.chill>=2?.75:1)-a.speed*(a.status.chill>=2?.75:1)||slotOrder(a,b))[0];if(mode==='attacker'){for(let i=s.log.length-1;i>=0;i--){const e=s.log[i];if(e.type==='damage'&&e.targetId===actor.id&&(e.amount>0||e.absorbed>0)){const target=foes.find(u=>u.id===e.unitId);if(target)return target;}}return foes[0];}if(mode==='crowd')return [...foes].sort((a,b)=>foes.filter(u=>Math.abs(u.slot-b.slot)<=1).length-foes.filter(u=>Math.abs(u.slot-a.slot)<=1).length||slotOrder(a,b))[0];if(mode==='previous-column'){const previous=previousColumn(s,actor,foes);if(previous!==null)return foes.find(u=>columnOf(u)===previous);}
 const candidates=COLUMNS.map((slots,index)=>{const members=foes.filter(u=>slots.includes(u.slot)),front=slots.find(x=>x<2),gap=front!==undefined&&!foes.some(u=>u.slot===front);return{members,index,score:mode==='cold-column'?members.reduce((n,u)=>n+u.status.chill,0):mode==='gap-column'?members.length+(gap?5:0):members.length};}).filter(c=>c.members.length).sort((a,b)=>b.score-a.score||a.index-b.index);return candidates[0]?.members[0]||foes[0];}
function physicalTargets(s,actor,kind,targetId){const ops=actor.actions[kind]||[],foes=s.units.filter(u=>alive(u)&&u.side!==actor.side).sort(slotOrder),target=foes.find(u=>u.id===targetId);if(!target)return[];const ids=new Set();for(const o of ops){let list=o.target==='all'?foes:o.target==='column'?foes.filter(u=>columnOf(u)===(o.column??columnOf(target))):o.target==='adjacent'?[target,...foes.filter(u=>u.id!==target.id).sort((a,b)=>Math.abs(a.slot-target.slot)-Math.abs(b.slot-target.slot)||slotOrder(a,b)).slice(0,2)]:o.target==='single'?[target]:[];for(const u of list.slice(0,o.maxTargets??5))ids.add(u.id);}return[...ids];}
export function expeditionBossPlan(value){const s=restoreExpeditionCombat(value),actor=expeditionCombatTurn(s);if(!actor?.boss||actor.side!=='enemy')return null;const gardenId=actor.speciesId.endsWith('-boss')?actor.speciesId.slice(0,-5):'',definition=Object.hasOwn(EXPEDITION_BOSS_BEHAVIORS,gardenId)?EXPEDITION_BOSS_BEHAVIORS[gardenId]:null;if(!definition)return null;const index=(s.round-1)%definition.steps.length,stage=definition.steps[index];let kind=stage.kind,target=select(s,actor,kind,stage.target),reason='cycle';
 // A real previous-round warning overrides cosmetic phase recovery. It does not
 // grant a cast or damage: the ordinary accepted command still costs one turn.
 const previous=s.warnings.filter(w=>w.ownerId===actor.id&&w.issuedRound===s.round-1).sort((a,b)=>a.slot-b.slot||a.key.localeCompare(b.key));for(const warning of previous){if(['attack','skill1'].includes(warning.kind)){const allowed=availableTargets(s,actor,warning.kind).find(u=>u.id===warning.targetId);if(allowed){kind=warning.kind;target=allowed;reason='earned-warning';break;}}else if(warning.kind==='counter'&&actor.actions.skill1.some(o=>o.type==='counter')){kind='skill1';target=select(s,actor,kind,'front');reason='earned-counter-warning';break;}}
 if(kind!=='guard'&&!target){kind='guard';reason='no-active-target';}const recovery=kind==='guard';return {gardenId,bossId:actor.id,bossName:definition.name,phase:reason==='cycle'?stage.phase:reason==='earned-warning'?'이미 예고한 공격':reason==='earned-counter-warning'?'이미 예고한 반격 재준비':stage.phase,phaseIndex:index,cycleLength:definition.steps.length,tier:actor.hp<=actor.maxHp*.5?2:1,kind,targetId:kind==='guard'?null:target?.id||null,targetIds:kind==='guard'?[]:physicalTargets(s,actor,kind,target?.id),tell:reason==='earned-warning'?'지난 라운드에 예고한 같은 개체·열의 공격입니다. 방어와 교대를 확인하세요.':reason==='earned-counter-warning'?'지난 라운드에 예고한 상대를 향해 유한 반격을 다시 준비합니다.':stage.tell,nextTell:definition.steps[(index+1)%definition.steps.length].tell,recovery,reason};}
export function expeditionBossCommand(state,actionId){if(typeof actionId!=='string'||!/^[A-Za-z0-9_.:-]{1,128}$/.test(actionId)||['__proto__','prototype','constructor'].includes(actionId))throw Error('Invalid expedition boss action identity');const plan=expeditionBossPlan(state);return plan?{id:actionId,unitId:plan.bossId,kind:plan.kind,...(plan.targetId?{targetId:plan.targetId}:{})}:null;}
