import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createMotion} from '../src/motion.js';
const root=new THREE.Group(),leg=new THREE.Group(),arm=new THREE.Group();
root.add(leg,arm);const rig=createMotion(root,[leg],[arm]);
root.position.set(3,0,4);root.rotation.y=.7;
const before=root.position.clone(),facing=root.rotation.y,count=root.children.length;
for(let i=0;i<60;i++)rig.update(1/60,.025,.025);
assert.ok(root.userData.motion.phase>0);
const phase=root.userData.motion.phase;
for(let i=0;i<60;i++)rig.update(1/60,0,0);
assert.equal(root.userData.motion.phase,phase,'No traveling gait while stationary');
assert.ok(root.userData.motion.pace<.001);
for(let i=0;i<30;i++)rig.update(1/60,0,0,{type:'caster',state:'tell',timer:.05});
assert.ok(arm.rotation.x<-.9,'Caster must visibly raise its arm before firing');
assert.deepEqual(root.position,before,'Visual pose must never move the collider');
assert.equal(root.rotation.y,facing,'Visual pose must never change committed aim');
assert.equal(root.children.length,count,'No per-frame rig allocation');
rig.reset();assert.equal(arm.rotation.x,0);assert.equal(rig.body.scale.y,1);
console.log('Distance gait, idle settling, caster anticipation and collider/aim isolation passed.');
