import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import './style.css';
import './journey.css';
import {ROOMS,EXIT,LAW_NAMES,rewardOptions,canUseExit} from './journey.js';
import {createWarden,tickWarden} from './warden.js';
import './mobile.css';
import {createTouchControls} from './touch.js';
const mobileDevice=matchMedia('(any-pointer: coarse)').matches||navigator.maxTouchPoints>0;
import {createMotion} from './motion.js';
import {createVFX,FX_COLORS} from './vfx.js';
import {coverBricks,segmentHitsCover} from './collision.js';
import {disposeObject} from './resources.js';
import {createSeedEvolution,LAW_PRESENTATION} from './evolution.js';
const $=s=>document.querySelector(s), V=THREE.Vector3;
const renderer=new THREE.WebGLRenderer({canvas:$('#game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobileDevice?1:1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#182932');scene.fog=new THREE.FogExp2('#192e38',.026);
const vfx=createVFX(scene,{mobile:mobileDevice});
const camera=new THREE.PerspectiveCamera(39,1,.1,100);const look=new V(0,0,0);camera.position.set(16,22,22);camera.lookAt(look);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(1,1),.42,.5,1.1));composer.addPass(new OutputPass());
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.22;
scene.add(new THREE.HemisphereLight(0x9ebbd0,0x172419,1.15));let sun=new THREE.DirectionalLight(0xc4dfef,2.1);sun.position.set(-9,17,6);sun.castShadow=true;sun.shadow.mapSize.set(mobileDevice?1024:2048,mobileDevice?1024:2048);Object.assign(sun.shadow.camera,{left:-16,right:16,top:16,bottom:-16,far:50});sun.shadow.normalBias=.035;scene.add(sun);
const texloader=new THREE.TextureLoader(), stone=texloader.load(import.meta.env.BASE_URL+'assets/garden-stone.png'),normal=texloader.load(import.meta.env.BASE_URL+'assets/garden-stone-normal.png');stone.colorSpace=THREE.SRGBColorSpace;for(let t of [stone,normal]){t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(.34,.34);t.anisotropy=8;}
const mats={stone:new THREE.MeshStandardMaterial({color:0xb1b9b8,map:stone,normalMap:normal,normalScale:new THREE.Vector2(.4,.4),roughness:.3,metalness:.12}),dark:new THREE.MeshStandardMaterial({color:0x707972,roughness:.9,map:stone}),root:new THREE.MeshStandardMaterial({color:0x3b3528,roughness:.9}),leaf:new THREE.MeshStandardMaterial({color:0x3e6242,roughness:.72,side:THREE.DoubleSide}),jade:new THREE.MeshStandardMaterial({color:0x91f2c0,emissive:0x38ffb0,emissiveIntensity:2.8,roughness:.2}),amber:new THREE.MeshStandardMaterial({color:0xffdb83,emissive:0xff970f,emissiveIntensity:3}),armor:new THREE.MeshStandardMaterial({color:0xd7cbae,map:stone,roughness:.57}),enemy:new THREE.MeshStandardMaterial({color:0xa48969,map:stone,roughness:.7}),black:new THREE.MeshStandardMaterial({color:0x536160,map:stone,roughness:.5})};
for(const id of ['seed','reflect','split','chain'])mats['shot-'+id]=new THREE.MeshBasicMaterial({color:new THREE.Color(FX_COLORS[id]).multiplyScalar(2),toneMapped:false});
const sharedDynamicMaterials=new Set(Object.values(mats));
function release(object){disposeObject(object,sharedDynamicMaterials);}
function mesh(geo,mat,parent,x=0,y=0,z=0){let m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
const box=(p,x,y,z,w,h,d,m=mats.stone)=>mesh(new THREE.BoxGeometry(w,h,d),m,p,x,y,z);
const orb=(p,x,y,z,r,m)=>mesh(new THREE.IcosahedronGeometry(r,1),m,p,x,y,z);
function limb(p,a,b,r,m=mats.root,r2=r*.65){let av=new V(...a),bv=new V(...b),v=bv.clone().sub(av);let ob=mesh(new THREE.CylinderGeometry(r2,r,v.length(),7),m,p);ob.position.copy(av.add(bv).multiplyScalar(.5));ob.quaternion.setFromUnitVectors(new V(0,1,0),v.normalize());return ob;}
function path(points,r,mat,parent=scene){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new V(...p))),Math.max(10,points.length*6),r,5,false),mat,parent);}
let randseed=487;function rng(){randseed=(randseed*1664525+1013904223)>>>0;return randseed/4294967296;}
const terrain=new THREE.Group();scene.add(terrain);box(terrain,0,-.7,0,22,1.4,18,mats.dark);
for(let x=-10.5;x<11;x+=1.5)for(let z=-8.5;z<9;z+=1.5){let t=box(terrain,x,-.035+rng()*.025,z,1.47,.2,1.47);t.rotation.y=(rng()-.5)*.035;}
const watermat=new THREE.MeshStandardMaterial({color:0x59777f,roughness:.08,metalness:.82,transparent:true,opacity:.42});for(let i=0;i<45;i++){let p=mesh(new THREE.CircleGeometry(.3+rng()*1.2,16),watermat,terrain,(rng()-.5)*20,.08,(rng()-.5)*16);p.rotation.x=-Math.PI/2;p.scale.y=.35+rng()*.6;}
const leafShape=new THREE.Shape();leafShape.moveTo(0,0);leafShape.bezierCurveTo(-.17,.2,-.16,.42,0,.62);leafShape.bezierCurveTo(.16,.42,.17,.2,0,0);const leafGeo=new THREE.ShapeGeometry(leafShape,5);const leafMats=[0x183f31,0x395b36,0x17372c,0x516443].map(color=>new THREE.MeshStandardMaterial({color,roughness:.87,side:THREE.DoubleSide}));const petalMat=new THREE.MeshStandardMaterial({color:0xe7e9d5,roughness:.65});
function foliage(x,z,scale=1){let g=new THREE.Group();g.position.set(x,.16,z);terrain.add(g);for(let i=0;i<9;i++){let a=i*2.4+rng()*.4;let l=mesh(leafGeo,leafMats[i%4],g,0,.02,0);l.rotation.set(-1.05-rng()*.45,a,(rng()-.5)*.8);l.scale.setScalar(.45+rng()*.6);if(i===0&&rng()>.55){for(let j=0;j<5;j++){let a=j*6.28/5;let petal=mesh(new THREE.SphereGeometry(.065,5,3),petalMat,g,Math.cos(a)*.065,.3,Math.sin(a)*.065);petal.scale.set(.6,.25,1);}orb(g,0,.3,0,.025,mats.armor);}}g.scale.setScalar(scale);return g;}
for(let i=0;i<660;i++){let x=(rng()-.5)*23,z=(rng()-.5)*19;if(Math.abs(x)>9||Math.abs(z)>7||rng()<.07)foliage(x,z,.6+rng()*.75);}
function wall(x,z,axis,count,height=1){for(let row=0;row<height;row++)for(let i=0;i<count;i++){let xx=x+(axis==='x'?i*1.05:0),zz=z+(axis==='z'?i*1.05:0);let b=box(terrain,xx,row*.56+.35,zz,axis==='x'?1:.67,.53,axis==='z'?1:.67);b.rotation.y=(rng()-.5)*.09;}}
wall(-11,-9,'x',22,3);wall(-11,-8,'z',17,2);wall(11,-8,'z',17,2);wall(-10,9,'x',21,1);
for(let x of [-10,-5,0,5,10]){box(terrain,x,1.35,-9,.9,2.7,.9);box(terrain,x,2.75,-9,1.08,.22,1.08);}for(let z of [-5,0,5,9])for(let x of [-11,11]){box(terrain,x,1.05,z,.9,2.1,.9);box(terrain,x,2.15,z,1.1,.2,1.1);}
const obstacles=[],roomCover=new THREE.Group();scene.add(roomCover);
for(let i=0;i<27;i++){let x=(rng()-.5)*21,z=(i%2?1:-1)*8.7;path([[x,0,z],[x+.6,.12,z-1],[x+.1,.17,z-2],[x+1,.15,z-2.4]],.06+rng()*.07,mats.root);}
function lantern(x,z,y=.6){let g=new THREE.Group();g.position.set(x,y,z);terrain.add(g);box(g,0,.15,0,.44,.12,.44,mats.black);box(g,0,.77,0,.5,.12,.5,mats.black);for(let a of [-1,1])for(let b of [-1,1])limb(g,[a*.18,.2,b*.18],[a*.18,.72,b*.18],.025,mats.black);orb(g,0,.45,0,.14,mats.amber);let light=new THREE.PointLight(0xffad45,14,6,2);light.position.y=.55;g.add(light);return g;}
for(let p of [[-10,-7],[-6,-8],[1,-8],[9,-7],[-10,4],[10,5],[7,8]])lantern(...p);
// Ruined shrine, distant bridges and silhouettes frame the playable stone garden.
for(let x of [-7.8,-4.7]){box(terrain,x,2.2,-10,1,4.4,1.3);box(terrain,x,4.5,-10,1.4,.4,1.5);}let arch=mesh(new THREE.TorusGeometry(1.55,.42,7,12,Math.PI),mats.stone,terrain,-6.25,3.8,-10);arch.rotation.z=0;
let statue=new THREE.Group();statue.position.set(-6.25,.4,-9.8);terrain.add(statue);mesh(new THREE.ConeGeometry(.6,2.1,7),mats.armor,statue,0,1.05,0);orb(statue,0,2.4,0,.32,mats.armor);limb(statue,[-.5,1.7,0],[-.2,1.1,.3],.15,mats.armor);limb(statue,[.5,1.7,0],[.2,1.1,.3],.15,mats.armor);
for(let i=0;i<9;i++){let x=-18+rng()*36,z=-14-rng()*10;path([[x,-2,z],[x+.5,2,z],[x-.6,6,z],[x+1,10,z]],.32,mats.root);for(let k=0;k<5;k++){let crown=orb(scene,x+(rng()-.5)*5,7+rng()*4,z+(rng()-.5)*4,1.8,mats.leaf);crown.scale.y=.6;}}
for(let x=3;x<22;x+=3.4){box(scene,x,-.8,-18,1,8,1,mats.dark);box(scene,x,3.3,-18,3.5,.6,2,mats.stone);}
// Broken edges, engraved garden seals and climbing roots give the garden a history.
for(let i=0;i<190;i++){let x=(rng()-.5)*22,z=(rng()-.5)*18;if(Math.abs(x)>9.3||Math.abs(z)>7.5){let rock=orb(terrain,x,.14,z,.1+rng()*.2,mats.stone);rock.scale.set(1,.6,1.3);rock.rotation.set(rng(),rng(),rng());}}
for(let radius of [.52,.63,.82,1.06]){let seal=mesh(new THREE.TorusGeometry(radius,.016,4,64),mats.armor,terrain,0,.09,.5);seal.rotation.x=Math.PI/2;}
for(let i=0;i<12;i++){let a=i*Math.PI/6;limb(terrain,[Math.cos(a)*.85,.09,.5+Math.sin(a)*.85],[Math.cos(a)*1.02,.09,.5+Math.sin(a)*1.02],.012,mats.armor);}
for(let x of [-10,-5,0,5,10]){for(let j=0;j<3;j++){let z=-9.4+j*.22;path([[x-.3,-.8,z],[x+.3,.5,z],[x-.2,1.2,z],[x+.3,2.5,z]],.035+j*.015,mats.root);for(let k=0;k<5;k++){let leaf=mesh(leafGeo,leafMats[k%4],terrain,x+Math.sin(k*2)*.3,k*.42,z+.45);leaf.rotation.set(.1,k,1);leaf.scale.setScalar(.6);}}}
// Terrace foundation continues down into the ravine rather than ending as a floating slab.
for(let x=-11;x<11;x+=1.4){box(terrain,x,-1.7,9,1.3,2.8,.8);if(Math.round(x)%3===0)path([[x,.6,9.4],[x+.3,-1,9.6],[x-.4,-3.1,9.3]],.12,mats.root);}
for(let z=-9;z<9;z+=1.4)for(let x of [-11,11])box(terrain,x,-1.7,z,.8,2.8,1.3);
const pool=mesh(new THREE.PlaneGeometry(65,65),new THREE.MeshStandardMaterial({color:0x172d35,normalMap:normal,normalScale:new THREE.Vector2(.015,.015),roughness:.68,metalness:.12}),scene,0,-3.4,0);pool.rotation.x=-Math.PI/2;
// Overhanging garden growth softens the square terrace and catches the moonlight.
for(let side of [-1,1])for(let j=0;j<8;j++){
 let x=side*(11.6+rng()*1.8),z=-8+j*2.7;
 path([[x,-3,z],[x-.35*side,.4,z],[x-side*.9,2.3,z+.4],[x-side*1.3,3.6,z+.8]],.10+rng()*.08,mats.root,terrain);
 for(let k=0;k<22;k++){
  let l=mesh(leafGeo,leafMats[k%4],terrain,x+(rng()-.5)*2,1.3+rng()*2.4,z+(rng()-.5)*2.4);
  l.rotation.set(-.5-rng(),rng()*6.28,rng()*2);l.scale.set(1.1+rng()*.9,1+rng()*1.6,1);
 }
}
for(let j=0;j<17;j++){
 let x=-11+rng()*22,z=-9-rng()*1.4;
 for(let k=0;k<12;k++){let l=mesh(leafGeo,leafMats[k%4],terrain,x+(rng()-.5),.5+rng()*2.7,z+(rng()-.5));l.rotation.set(rng()*2,rng()*6.28,rng());l.scale.setScalar(.7+rng());}
}
const bannerMat=new THREE.MeshStandardMaterial({color:0x193e3b,roughness:1,side:THREE.DoubleSide});
for(let x of [-8.5,-3.8]){let cloth=new THREE.PlaneGeometry(.95,2.1,5,10);let a=cloth.attributes.position;for(let i=0;i<a.count;i++)a.setZ(i,Math.sin(a.getY(i)*5+a.getX(i)*2)*.07);cloth.computeVertexNormals();mesh(cloth,bannerMat,terrain,x,2,-9.05);limb(terrain,[x-.6,3.05,-9],[x+.6,3.05,-9],.035,mats.armor);let sigil=mesh(new THREE.TorusGeometry(.22,.025,4,20),mats.armor,terrain,x,2,-8.94);for(let side of [-1,1])limb(terrain,[x,1.5,-8.94],[x+side*.26,2.3,-8.94],.018,mats.armor);}
// Batch immovable masonry and plants by material, retaining lantern lights.
terrain.updateMatrixWorld(true);const batches=new Map(),staticMeshes=[];terrain.traverse(o=>{if(o.isMesh){staticMeshes.push(o);let geo=o.geometry.clone();if(geo.index)geo=geo.toNonIndexed();geo.applyMatrix4(o.matrixWorld);if(!batches.has(o.material))batches.set(o.material,[]);batches.get(o.material).push(geo);}});for(let o of staticMeshes)o.removeFromParent();for(let [mat,geos]of batches){let merged=mergeGeometries(geos,false);if(merged){let ob=new THREE.Mesh(merged,mat);ob.castShadow=ob.receiveShadow=true;scene.add(ob);}for(let geo of geos)geo.dispose();}
const motes=[];for(let i=0;i<45;i++){let m=orb(scene,(rng()-.5)*28,rng()*4,(rng()-.5)*23,.025,i%3?mats.jade:mats.amber);m.userData.seed=rng()*9;motes.push(m);}
function makePlayer(){let g=new THREE.Group();scene.add(g);const torso=orb(g,0,.65,0,.43,mats.root);torso.scale.set(1,1.2,.75);for(let side of [-1,1]){let sh=orb(g,side*.37,.79,0,.27,mats.armor);sh.scale.set(.65,1.3,.8);limb(g,[side*.4,.65,0],[side*.52,.27,.08],.11,mats.root);orb(g,side*.53,.22,.06,.13,mats.armor);}let heart=orb(g,0,.78,.32,.22,mats.jade);let rim=mesh(new THREE.TorusGeometry(.25,.04,6,16),mats.armor,g,0,.78,.3);orb(g,0,1.18,0,.23,mats.armor);for(let i=0;i<5;i++){let a=(i-2)*.5;let leaf=mesh(new THREE.ConeGeometry(.12,.56,5),mats.leaf,g,Math.sin(a)*.17,1.49,.02);leaf.rotation.z=-a*.8;}let legs=[];for(let side of [-1,1]){let l=new THREE.Group();g.add(l);l.position.set(side*.23,.37,0);limb(l,[0,0,0],[side*.12,-.26,.13],.13,mats.root);let foot=orb(l,side*.13,-.3,.22,.15,mats.armor);foot.scale.set(1,.6,1.5);legs.push(l);}let light=new THREE.PointLight(0x7affba,2,3);light.position.set(0,1,.3);g.add(light);// A luminous seed is readable from every aiming direction.
let back=orb(g,0,.8,-.29,.145,mats.jade);back.scale.set(1,1.25,.45);
let halo=mesh(new THREE.TorusGeometry(.24,.022,5,24),mats.armor,g,0,.8,-.31);
for(let side of [-1,1]){path([[side*.2,.45,-.16],[side*.29,.7,-.23],[side*.19,1,-.2]],.018,mats.jade,g);let plate=orb(g,side*.22,.61,-.18,.24,mats.armor);plate.scale.set(.65,1,.6);}
g.userData={legs,heart,halo};return g;}
const player=makePlayer();player.scale.setScalar(1.35);player.position.set(0,0,5);let hp=100,dash=0,invuln=0,shootCD=0,elapsed=0,stage=0,mode='ready',paused=false,kills=0;const chosen=new Set(),mutated=new Set();let roomCleared=false,exitOpen=false;let enemies=[],shots=[],effects=[],enemyShots=[];const keys=new Set();let mouseDown=false,aim=new V(0,0,-3),pointer=new THREE.Vector2(0,0),hasPointer=false;const ray=new THREE.Raycaster(),plane=new THREE.Plane(new V(0,1,0),0);
const touch=createTouchControls(()=>mode==='playing'&&!paused);
const playerMotion=createMotion(player,player.userData.legs);const growth=createSeedEvolution(player,playerMotion.body);let evolutionTime=0;const evolutionDuration=1.4;
function ring(parent,r,color){let mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.75,side:THREE.DoubleSide});let m=mesh(new THREE.RingGeometry(r-.035,r,48),mat,parent);m.rotation.x=-Math.PI/2;m.position.y=.12;return m;}
function enemy(type,x,z){let g=new THREE.Group();scene.add(g);g.position.set(x,0,z);let legs=[],arms=[];if(type==='hound'){let body=orb(g,0,.68,0,.56,mats.enemy);body.scale.set(.8,.75,1.5);orb(g,0,.66,.7,.36,mats.enemy);let snout=orb(g,0,.52,1,.21,mats.enemy);snout.scale.z=1.5;for(let side of [-1,1]){orb(g,side*.18,.76,.95,.055,mats.amber);for(let zz of [-.5,.5]){let l=new THREE.Group();l.position.set(side*.35,.55,zz);g.add(l);limb(l,[0,0,0],[side*.16,-.28,.03],.12,mats.enemy);limb(l,[side*.16,-.28,.03],[side*.2,-.5,.21],.09,mats.enemy);legs.push(l);}}for(let i=0;i<6;i++){let s=mesh(new THREE.ConeGeometry(.12,.58,5),mats.enemy,g,0,1.04,-.65+i*.23);s.rotation.x=-.6;}path([[0,.65,-.65],[.2,.7,-1.2],[.5,.9,-1.5]],.09,mats.root,g);}else{mesh(new THREE.ConeGeometry(.52,1.45,6,1,true),mats.black,g,0,.98,0);orb(g,0,1.85,0,.22,mats.enemy);for(let side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*.17,.65,0);g.add(leg);limb(leg,[0,0,0],[side*.15,-.53,.13],.075,mats.black);legs.push(leg);const arm=new THREE.Group();arm.position.set(side*.28,1.5,0);g.add(arm);limb(arm,[0,0,0],[side*.18,-.45,.3],.1,mats.enemy);arms.push(arm);let horn=mesh(new THREE.ConeGeometry(.09,.75,4),mats.amber,g,side*.17,2.2,0);horn.rotation.z=-side*.3;}orb(g,0,1.16,.37,.18,mats.amber);limb(g,[.6,.05,.25],[.6,2,.25],.035,mats.root);}if(type==='hound'){for(let side of [-1,1]){for(let i=0;i<4;i++){let plate=orb(g,side*.3,.92,-.45+i*.29,.22,mats.enemy);plate.scale.set(.8,.32,1.25);plate.rotation.z=side*.4;let spike=mesh(new THREE.ConeGeometry(.07,.36,5),mats.armor,g,side*.36,1.05,-.4+i*.3);spike.rotation.z=-side*.7;}for(let tooth=0;tooth<3;tooth++){let fang=mesh(new THREE.ConeGeometry(.026,.12,4),mats.armor,g,side*.13,.45,.91+tooth*.09);fang.rotation.z=Math.PI;}}}else{for(let side of [-1,1]){let shoulder=orb(g,side*.3,1.53,0,.21,mats.enemy);shoulder.scale.set(.8,.55,1.4);for(let i=0;i<2;i++){let crown=mesh(new THREE.ConeGeometry(.055,.45+i*.2,4),mats.amber,g,side*(.06+i*.18),2.24-i*.13,.05);crown.rotation.z=-side*(.12+i*.25);}}}g.scale.setScalar(type==='hound'?1.3:1.22);let e={g,type,hp:type==='hound'?96+stage*15:116+stage*20,timer:.35+rng()*.7,state:'stalk',dir:new V(),legs,phase:rng()*6,hit:0};e.motion=createMotion(g,legs,arms);e.ring=ring(g,type==='hound'?.9:1.1,0xed7d30);e.ring.material.opacity=.25;
let tellMat=new THREE.MeshBasicMaterial({color:0xff932d,transparent:true,opacity:.2,depthWrite:false,side:THREE.DoubleSide});
let tell=mesh(type==='hound'?new THREE.PlaneGeometry(.9,4.8):new THREE.RingGeometry(1.1,1.3,48),tellMat,g,0,.095,type==='hound'?2.7:0);tell.rotation.x=-Math.PI/2;tell.visible=false;e.tell=tell;
enemies.push(e);}
const gate=new THREE.Group();gate.position.set(EXIT.x,0,EXIT.z);scene.add(gate);
const gateRing=ring(gate,1,0xa9ffda);const gateHalo=mesh(new THREE.TorusGeometry(.7,.08,6,40),mats.jade,gate,0,1.1,0);gate.visible=false;
document.body.insertAdjacentHTML('beforeend','<button id="exit-room" hidden>다음 방으로 · E</button><div id="boss-hud" hidden><strong>기억의 문지기</strong><div><i></i></div><small></small></div>');
$('#exit-room').onclick=useExit;$('#stages').innerHTML=ROOMS.map(()=>'<span>♧</span>').join('<i></i>');
function drawRoom(){for(const child of [...roomCover.children])release(child);obstacles.splice(0,obstacles.length,...ROOMS[stage].covers.map(o=>({...o})));for(const o of obstacles)for(const b of coverBricks(o))box(roomCover,b.x,b.y,b.z,b.w,b.h,b.d);}
function wave(){
 vfx.clear();
 roomCleared=false;exitOpen=false;gate.visible=false;$('#exit-room').hidden=true;$('#toast').textContent='';
 for(const p of [...shots,...enemyShots,...effects])release(p.ob);shots=[];enemyShots=[];effects=[];
 drawRoom();player.position.set(0,0,5);playerMotion.reset();invuln=Math.max(invuln,.8);
 for(const [type,x,z] of ROOMS[stage].enemies){if(type==='warden'){const e=createWarden(scene,mats);e.g.position.set(x,0,z);enemies.push(e);}else enemy(type,x,z);}
 $('#encounter').textContent=`${String(stage+1).padStart(2,'0')} · ${ROOMS[stage].name}`;
 [...document.querySelectorAll('#stages span')].forEach((n,i)=>n.classList.toggle('active',i<=stage));$('#boss-hud').hidden=stage!==4;
}
function openExit(){exitOpen=true;gate.visible=true;$('#toast').textContent=stage===4?'문지기가 쓰러졌다 · 빛나는 출구로 돌아가세요':'법칙이 몸에 새겨졌다 · 빛나는 출구로 이동하세요';}
function useExit(){if(!canUseExit({open:exitOpen,mode,paused,x:player.position.x,z:player.position.z}))return;touch.reset();keys.clear();mouseDown=false;exitOpen=false;gate.visible=false;$('#exit-room').hidden=true;$('#toast').textContent='';if(stage===4){mode='won';showEnd(true);}else{stage++;wave();}}
function bossBolt(pos,dir,bounces){const start=pos.clone().addScaledVector(dir,1.25);const ob=orb(scene,start.x,.65,start.z,.16,mats.amber);enemyShots.push({ob,dir,life:5,bounces,speed:5.2,damage:18});}

function burst(pos,color,n=12){vfx.burst(pos,color,n);}
function line(a,b){vfx.arc(a,b);}
function damageEnemy(e,amount,chaining=true){if(e.state==='recover')amount*=1.35;e.hp-=amount;e.hit=.14;vfx.impact(e.g.position,chaining?([...chosen][0]||'seed'):'chain');if(chaining&&chosen.has('chain')){let nearby=enemies.filter(o=>o!==e&&o.hp>0&&o.g.position.distanceTo(e.g.position)<4).sort((a,b)=>a.g.position.distanceTo(e.g.position)-b.g.position.distanceTo(e.g.position)).slice(0,mutated.has('chain')?3:2);for(let o of nearby){line(e.g.position,o.g.position);damageEnemy(o,amount*.5,false);}}if(e.hp<=0&&!e.dead){e.dead=true;kills++;vfx.impact(e.g.position,'amber',true);release(e.g);}}
function projectile(pos,dir,fragment=false,ignoreEnemy=null){let ob=orb(scene,pos.x,.67,pos.z,fragment?.07:.12,mats.jade);ob.scale.z=1.8;const tint=fragment?'split':([...chosen][0]||'seed');ob.material=mats['shot-'+tint];shots.push({ob,dir:dir.clone(),life:2.3,bounces:0,fragment,ignoreEnemy,tint,trailTime:0,trailPos:ob.position.clone()});}
function hitPlayer(amount){if(invuln>0||mode!=='playing')return;hp=Math.max(0,hp-amount);invuln=.65;burst(player.position,'amber',16);cameraShake=.18;if(hp<=0){mode='dead';showEnd(false);}}
let cameraShake=0;const aimRing=ring(scene,.22,0xa4f8db);aimRing.material.opacity=.5;aimRing.visible=false;
function collide(pos,r=.4){pos.x=THREE.MathUtils.clamp(pos.x,-10+r,10-r);pos.z=THREE.MathUtils.clamp(pos.z,-8+r,8-r);for(let o of obstacles){let dx=pos.x-o.x,dz=pos.z-o.z,wx=o.w/2+r,wz=o.d/2+r;if(Math.abs(dx)<wx&&Math.abs(dz)<wz){if(wx-Math.abs(dx)<wz-Math.abs(dz))pos.x=o.x+Math.sign(dx||1)*wx;else pos.z=o.z+Math.sign(dz||1)*wz;}}}
function cardChoice(){
 touch.reset();keys.clear();mouseDown=false;mode='cards';const isMutation=stage===3;
 const notes={reflect:'벽에서 두 번 반사되는 탄환',split:'적중하면 세 파편으로 갈라지는 탄환',chain:'가까운 두 적에게 이어지는 번개'};
 const upgrades={reflect:'반사 횟수 2 → 4 · 탄 피해 +15%',split:'파편 3 → 5 · 탄 피해 +15%',chain:'연쇄 대상 2 → 3 · 탄 피해 +15%'};
 $('#overlay').hidden=false;$('#overlay').innerHTML=`<p>${ROOMS[stage].name} · 통과</p><h2>${isMutation?'법칙의 변이':stage===0?'뿌리의 법칙':'새로운 법칙'}</h2><p>${isMutation?'보유한 법칙 하나를 강화합니다':'새 법칙은 이전 법칙과 함께 작동합니다'} · 생명력 20 회복</p><div class="cards">${rewardOptions(stage,[...chosen]).map(id=>`<button class="card" data-choice="${id}"><em>${{reflect:'◈',split:'✣',chain:'ϟ'}[id]}</em><strong>${LAW_NAMES[id]}</strong><p>${isMutation?'MUTATION':id.toUpperCase()}</p><small>${isMutation?upgrades[id]:notes[id]}</small></button>`).join('')}</div>`;
 document.querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>{if(mode!=='cards')return;const id=button.dataset.choice;if(isMutation)mutated.add(id);else chosen.add(id);document.querySelector(`[data-rule="${id}"]`).classList.add('active');hp=Math.min(100,hp+20);beginEvolution(id);});
}

function updateFormLabel(){ $('#form-label').textContent=[...chosen].map(id=>LAW_PRESENTATION[id].name+(mutated.has(id)?' ✧':'')).join(' · ')||'아직 이름 없는 씨드'; }
function beginEvolution(id){
  touch.reset();mode='evolving';evolutionTime=0;mouseDown=false;keys.clear();player.userData.dashTime=0;player.visible=true;playerMotion.reset();
  for(const p of [...shots,...enemyShots,...effects])release(p.ob);shots=[];enemyShots=[];effects=[];
  $('#overlay').hidden=true;$('#evolution').hidden=false;
  $('#evolution-title').textContent=LAW_PRESENTATION[id].name+(mutated.has(id)?' · 변이':'');
  $('#evolution-hint').textContent=LAW_PRESENTATION[id].hint;
  growth.select(chosen,mutated);updateFormLabel();vfx.clear();vfx.evolution(player.position,id);
}
function startGame(){
  if(mode!=='ready')return;
  keys.clear();mouseDown=false;mode='playing';paused=false;$('#overlay').hidden=true;wave();
}
function showIntro(){drawRoom();
  mode='ready';$('#overlay').classList.add('intro');$('#overlay').hidden=false;
  $('#overlay').innerHTML='<p class="eyebrow">SEED · 첫 발아</p><h2>잠든 정원을 깨우다</h2><p>네 개의 방을 지나, 당신의 법칙을 배우는 문지기를 만나세요.<br>적의 공격을 피한 뒤 드러나는 빈틈을 노려보세요.</p><div class="intro-controls"><span><kbd>W A S D</kbd> 이동</span><span><kbd>마우스</kbd> 조준 · 공격</span><span><kbd>SPACE</kbd> 회피</span></div><button id="start-game" class="primary">정원에 들어가기 <small>↵ ENTER</small></button>';
  if(touch.enabled){$('.intro-controls').innerHTML='<span><kbd>왼손 스틱</kbd> 이동</span><span><kbd>오른손 스틱</kbd> 조준 · 발사</span><span><kbd>◇ 버튼</kbd> 회피</span>';$('#start-game small').textContent='가로 화면 권장';}
  $('#start-game').onclick=()=>{$('#overlay').classList.remove('intro');startGame();};
  updateFormLabel();
}
function showEnd(win){touch.reset();$('#overlay').hidden=false;$('#overlay').innerHTML=`<p>${win?'기억의 문지기를 넘어':'씨앗은 다시 뿌리를 내립니다'}</p><h2>${win?'정원이 깨어납니다':'잠든 씨앗'}</h2><p>${win?'당신이 고른 법칙이 새로운 길을 열었습니다.':'돌과 뿌리 사이에서, 다시 한 번.'}<br>쓰러뜨린 파수꾼 ${kills} · ${Math.floor(elapsed)}초</p><button class="primary" id="restart">다시 시작</button>`;$('#restart').onclick=restart;}
function restart(){vfx.clear();touch.reset();for(let e of enemies)release(e.g);for(let p of [...shots,...enemyShots,...effects])release(p.ob);enemies=[];shots=[];enemyShots=[];effects=[];chosen.clear();mutated.clear();roomCleared=false;exitOpen=false;growth.reset();playerMotion.reset();player.visible=true;evolutionTime=0;$('#evolution').hidden=true;updateFormLabel();document.querySelectorAll('#rules>div').forEach(n=>n.classList.remove('active'));hp=100;dash=0;invuln=1;shootCD=0;mouseDown=false;keys.clear();player.userData.dashTime=0;stage=0;kills=0;elapsed=0;player.position.set(0,0,5);mode='playing';paused=false;$('#overlay').hidden=true;$('#pause').textContent='Ⅱ';$('#toast').textContent='';wave();}
function togglePause(){if(mode!=='playing'&&mode!=='evolving')return;paused=!paused;touch.reset();keys.clear();mouseDown=false;if(paused)player.visible=true;$('#pause').textContent=paused?'▶':'Ⅱ';$('#toast').textContent=paused?(touch.enabled?'일시 정지 · 오른쪽 위 ▶ 버튼으로 계속':'일시 정지 · P 또는 ▶ 버튼으로 계속'):'';}
window.addEventListener('keydown',e=>{if(['Space','KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat&&(e.code==='KeyP'||e.code==='Escape'))togglePause();if(e.code==='KeyE'&&!e.repeat)useExit();if(e.code==='Enter'&&mode==='ready'){$('#overlay').classList.remove('intro');startGame();}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();mouseDown=false;if(!paused&&(mode==='playing'||mode==='evolving'))togglePause();});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);hasPointer=true;});renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.button===0)mouseDown=true;});window.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')mouseDown=false;});$('#pause').onclick=togglePause;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&(mode==='playing'||mode==='evolving'))togglePause();});
function update(dt,time){
  touch.update(mode==='playing'&&!paused,dash);
if(mode==='evolving'){
  if(paused)return;
  evolutionTime=Math.min(evolutionDuration,evolutionTime+dt);
  const progress=evolutionTime/evolutionDuration;
  growth.update(dt,time,true,progress);$('#evolution').style.setProperty('--growth',progress);
  if(progress>=1){growth.update(0,time,false);$('#evolution').hidden=true;mode='playing';invuln=Math.max(invuln,.6);openExit();}
  return;
}
if(!paused)growth.update(dt,time,false);
if(mode!=='playing'||paused)return;const previousPlayer=player.position.clone();elapsed+=dt;dash=Math.max(0,dash-dt);invuln=Math.max(0,invuln-dt);shootCD-=dt;const move=new V();if(keys.has('KeyW'))move.add(new V(-.59,0,-.81));if(keys.has('KeyS'))move.add(new V(.59,0,.81));if(keys.has('KeyA'))move.add(new V(-.81,0,.59));if(keys.has('KeyD'))move.add(new V(.81,0,-.59));move.add(new V(touch.axes.move.x*.81+touch.axes.move.y*.59,0,-touch.axes.move.x*.59+touch.axes.move.y*.81)).clampLength(0,1);const touchAiming=Math.hypot(touch.axes.aim.x,touch.axes.aim.y)>.1;if(touchAiming){hasPointer=false;const origin=new V(player.position.x,0,player.position.z).project(camera);ray.setFromCamera(new THREE.Vector2(origin.x+touch.axes.aim.x*.25,origin.y-touch.axes.aim.y*.25*camera.aspect),camera);ray.ray.intersectPlane(plane,aim);}const touchDash=touch.consumeDash();if((keys.has('Space')||touchDash)&&dash===0){dash=2.4;invuln=.32;player.userData.dashTime=.2;player.userData.dashDir=move.lengthSq()?move.clone():aim.clone().sub(player.position).setY(0).normalize();vfx.burst(player.position,'seed',14);vfx.dash(player.position,player.rotation.y);player.userData.dashFX=0;}if(player.userData.dashTime>0){player.userData.dashTime-=dt;player.position.addScaledVector(player.userData.dashDir,dt*17);player.userData.dashFX+=dt;if(player.userData.dashFX>=.045){player.userData.dashFX=0;vfx.dash(player.position,player.rotation.y);}}else player.position.addScaledVector(move,dt*4.5);collide(player.position);if(hasPointer){ray.setFromCamera(pointer,camera);ray.ray.intersectPlane(plane,aim);}aimRing.visible=hasPointer||touchAiming;aimRing.position.set(aim.x,.11,aim.z);let aimdir=aim.clone().sub(player.position).setY(0).normalize();player.rotation.y=Math.atan2(aimdir.x,aimdir.z);playerMotion.update(dt,player.position.x-previousPlayer.x,player.position.z-previousPlayer.z,{dashing:player.userData.dashTime>0});player.userData.heart.scale.setScalar(1+Math.sin(time*5)*.08);player.visible=invuln<.5||Math.floor(time*20)%2===0;player.userData.halo.rotation.z=time*.4;
if((mouseDown||touchAiming)&&shootCD<=0&&!roomCleared){shootCD=.3;growth.fire();vfx.muzzle(player.position.clone().addScaledVector(aimdir,.65),aimdir,[...chosen][0]||'seed');projectile(player.position.clone().addScaledVector(aimdir,.6),aimdir);}
for(let e of enemies){if(e.dead)continue;if(e.type==='warden'){tickWarden(e,dt,time,player.position,[...chosen],{collide,bolt:bossBolt,hit:hitPlayer,burst});continue;}const previousEnemy=e.g.position.clone();let delta=player.position.clone().sub(e.g.position).setY(0),dist=delta.length();delta.normalize();e.tell.visible=e.state==='tell';e.tell.material.opacity=.12+Math.abs(Math.sin(time*9))*.17;e.timer-=dt;e.hit=Math.max(0,e.hit-dt);e.g.rotation.y=Math.atan2((e.state==='tell'||e.state==='commit'?e.dir:delta).x,(e.state==='tell'||e.state==='commit'?e.dir:delta).z);if(e.state==='stalk'){if(e.type==='hound'){e.g.position.addScaledVector(delta,dt*(1.65+stage*.15));if(e.timer<0&&dist<6){e.state='tell';e.timer=.7;e.dir.copy(delta);}}else{if(dist<4.8)e.g.position.addScaledVector(delta,-dt*.9);else if(dist>6.8)e.g.position.addScaledVector(delta,dt*.8);e.g.position.x+=delta.z*dt*.65*(e.phase<3?1:-1);e.g.position.z-=delta.x*dt*.65*(e.phase<3?1:-1);if(e.timer<0){e.state='tell';e.timer=.85;e.dir.copy(delta);}}}else if(e.state==='tell'){e.ring.material.opacity=.45+Math.sin(time*20)*.3;e.ring.scale.setScalar(1+(1-e.timer)*.3);if(e.timer<=0){e.state='commit';e.timer=e.type==='hound'?.48:.2;if(e.type==='caster'){for(let j=-1;j<=1;j++){let d=e.dir.clone().applyAxisAngle(new V(0,1,0),j*.17);let ob=orb(scene,e.g.position.x,.65,e.g.position.z,.13,mats.amber);enemyShots.push({ob,dir:d,life:4});}}}}else if(e.state==='commit'){if(e.type==='hound'){e.g.position.addScaledVector(e.dir,dt*8);if(e.g.position.distanceTo(player.position)<1)hitPlayer(19);}if(e.timer<=0){e.state='recover';e.timer=1.25;e.ring.material.opacity=.16;e.ring.scale.setScalar(1);}}else if(e.timer<=0){e.state='stalk';e.timer=.55+rng()*.65;}collide(e.g.position,.65);e.motion.update(dt,e.g.position.x-previousEnemy.x,e.g.position.z-previousEnemy.z,{type:e.type,state:e.state,timer:e.timer,hit:e.hit});e.tell.visible=e.state==='tell';}
for(let p of shots){p.life-=dt;p.ob.position.addScaledVector(p.dir,dt*(p.fragment?8:12));p.ob.rotation.y=Math.atan2(p.dir.x,p.dir.z);p.trailTime+=dt;if(p.trailTime>=.035){vfx.trail(p.trailPos,p.ob.position,p.tint,p.fragment);p.trailPos.copy(p.ob.position);p.trailTime=0;}let pos=p.ob.position;let wallHit=Math.abs(pos.x)>10||Math.abs(pos.z)>8;for(let o of obstacles){if(Math.abs(pos.x-o.x)<o.w/2+.1&&Math.abs(pos.z-o.z)<o.d/2+.1){wallHit=true;let dx=Math.abs(pos.x-o.x)/(o.w/2),dz=Math.abs(pos.z-o.z)/(o.d/2);if(dx>dz)p.dir.x*=-1;else p.dir.z*=-1;break;}}if(wallHit){if(chosen.has('reflect')&&p.bounces<(mutated.has('reflect')?4:2)){if(Math.abs(pos.x)>10)p.dir.x*=-1;if(Math.abs(pos.z)>8)p.dir.z*=-1;pos.x=THREE.MathUtils.clamp(pos.x,-9.95,9.95);pos.z=THREE.MathUtils.clamp(pos.z,-7.95,7.95);pos.addScaledVector(p.dir,.25);p.bounces++;vfx.reflect(pos,p.dir);p.trailPos.copy(pos);}else p.life=0;}for(let e of enemies){if(!e.dead&&e!==p.ignoreEnemy&&Math.hypot(e.g.position.x-pos.x,e.g.position.z-pos.z)<(e.type==='warden'?1.2:.9)){damageEnemy(e,(p.fragment?9:18)*(mutated.size?1.15:1));p.life=0;if(chosen.has('split')&&!p.fragment){vfx.split(pos,p.dir,mutated.has('split')?5:3);for(let angle of (mutated.has('split')?[-.8,-.4,0,.4,.8]:[-.65,0,.65]))projectile(pos.clone().addScaledVector(p.dir,.85),p.dir.clone().applyAxisAngle(new V(0,1,0),angle),true,e);}break;}}}
for(let p of enemyShots){p.life-=dt;const previous=p.ob.position.clone();p.ob.position.addScaledVector(p.dir,dt*(p.speed??(5+stage*.45)));const outside=Math.abs(p.ob.position.x)>10||Math.abs(p.ob.position.z)>8;
 if(segmentHitsCover(previous,p.ob.position,obstacles,.13)||outside){if(p.bounces>0){const next=p.ob.position;let flipX=Math.abs(next.x)>10,flipZ=Math.abs(next.z)>8;for(const o of obstacles)if(segmentHitsCover(previous,next,[o],.13)){if(Math.abs(previous.x-o.x)>=o.w/2+.13)flipX=true;else flipZ=true;break;}if(flipX)p.dir.x*=-1;if(flipZ)p.dir.z*=-1;p.ob.position.copy(previous);p.bounces--;}else p.life=0;continue;}
 if(Math.hypot(p.ob.position.x-player.position.x,p.ob.position.z-player.position.z)<.55){hitPlayer(p.damage??13);p.life=0;}}

for(let arr of [shots,enemyShots,effects])for(let i=arr.length-1;i>=0;i--){let p=arr[i];if(arr===effects){p.life-=dt;if(p.vel)p.ob.position.addScaledVector(p.vel,dt);p.ob.scale.setScalar(Math.max(.01,p.life/p.max));}if(p.life<=0){release(p.ob);arr.splice(i,1);}}
enemies=enemies.filter(e=>!e.dead);if(!enemies.length&&mode==='playing'&&!roomCleared){for(let p of enemyShots)release(p.ob);enemyShots=[];roomCleared=true;for(const p of shots)release(p.ob);shots=[];if(stage<4)cardChoice();else openExit();}
const boss=enemies.find(e=>e.type==='warden');if(boss){$('#boss-hud i').style.width=(boss.hp/boss.maxHp*100)+'%';$('#boss-hud small').textContent=boss.learned.length?'습득: '+boss.learned.map(id=>LAW_NAMES[id]).join(' · '):'생명 67% · 34%에서 당신의 법칙을 배웁니다';}else $('#boss-hud').hidden=true;const nearExit=canUseExit({open:exitOpen,mode,paused,x:player.position.x,z:player.position.z});$('#exit-room').hidden=!nearExit;$('#exit-room').textContent=stage===4?'정원 밖으로 · E':touch.enabled?'다음 방으로':'다음 방으로 · E';gateHalo.rotation.y=time*.6;$('#hpbar').style.width=hp+'%';$('#hptext').textContent=`${hp} / 100`;$('#dashbar').style.width=(1-dash/2.4)*100+'%';$('#dashtext').textContent=dash>0?dash.toFixed(1)+'s':'준비';}
let last=performance.now(),frames=[],frameCounter=0;function animate(now){requestAnimationFrame(animate);let raw=(now-last)/1000,dt=Math.min(raw,.04);last=now;frames.push(raw*1000);if(frames.length>180)frames.shift();update(dt,now*.001);if(!paused)vfx.update(dt);for(let m of motes)m.position.y+=Math.sin(now*.001+m.userData.seed)*dt*.08;look.lerp(new V(player.position.x*.1,0,player.position.z*.08),.035);camera.position.set(13.5+look.x,19.3,20+look.z);cameraShake=Math.max(0,cameraShake-dt);if(cameraShake>0)camera.position.x+=(rng()-.5)*cameraShake;camera.lookAt(look);renderer.info.autoReset=false;renderer.info.reset();composer.render();frameCounter++;}
function resize(){const w=document.documentElement.clientWidth,viewHeight=document.documentElement.clientHeight,h=touch.enabled&&viewHeight>w?Math.max(250,viewHeight-160):viewHeight;renderer.setSize(w,h,false);renderer.domElement.style.width='100%';renderer.domElement.style.height=h+'px';camera.aspect=w/h;camera.zoom=Math.min(1.18,camera.aspect/(touch.enabled&&h>w?1.25:.95));camera.updateProjectionMatrix();composer.setSize(w,h);if(touch.enabled&&mode==='playing'&&!paused)togglePause();}window.addEventListener('resize',resize);resize();showIntro();requestAnimationFrame(animate);
// Read-only live diagnostics for performance and real-input validation.
window.seedDebug={getState:()=>({vfx:vfx.state(),mode,paused,hp,stage:stage+1,room:ROOMS[stage].name,exit:{open:exitOpen,x:EXIT.x,z:EXIT.z,near:canUseExit({open:exitOpen,mode,paused,x:player.position.x,z:player.position.z})},mutated:[...mutated],kills,playerVisible:player.visible,touch:touch.state(),motion:{...player.userData.motion},evolution:growth.state(),rules:[...chosen],dash,invulnerable:invuln>0,player:{x:player.position.x,z:player.position.z},enemies:enemies.map(e=>({type:e.type,hp:e.hp,maxHp:e.maxHp,learned:e.learned,attacks:e.attacks,pattern:e.pattern,state:e.state,motion:{...e.g.userData.motion},facing:e.g.rotation.y,x:e.g.position.x,z:e.g.position.z})),projectiles:shots.length,enemyProjectiles:enemyShots.length,elapsed,fps:frames.length/(frames.reduce((a,b)=>a+b,0)/1000),frameMsP95:[...frames].sort((a,b)=>a-b)[Math.floor(frames.length*.95)],drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,coverBounds:obstacles.map(o=>({...o}))}),worldToScreen:(x,z)=>{let p=new V(x,.5,z).project(camera);const r=renderer.domElement.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}};
